# Generated by Django 5.2.7 on 2025-10-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('category', models.CharField(choices=[('BES', 'Bestie'), ('DRA', 'Drakonidy'), ('HYB', 'Hybrydy'), ('INS', 'Insektoidy'), ('ISTM', 'Istoty Magiczne'), ('ISTP', 'Istoty przeklęte'), ('OGR', 'Ogrowate'), ('REL', 'Relikty'), ('TRU', 'Trupojady'), ('UPI', 'Upiory'), ('WAM', 'Wampiry'), ('UNK', 'Nieznane')], default='TRU', max_length=5)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
