# Generated by Django 5.2.7 on 2025-10-15 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_monster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(choices=[('KRN', 'Korony'), ('ORN', 'Oreny'), ('FLO', 'Floreny')], default='KRN', max_length=3)),
                ('reward', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('OPN', 'Aktywne'), ('TKN', 'Przyjęte'), ('DON', 'Zakończone'), ('CAN', 'Anulowane')], default='OPN', max_length=3)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.monster')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.realm')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.town')),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
    ]
