# Generated by Django 5.2.7 on 2025-10-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
